services:
  mongodb:
    image: mongo:latest
    container_name: mongodbcontainer
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  web:
    image: tagsapi:latest
    container_name: tags-api
    build:
      context: .
      dockerfile: TagsApi/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb 
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Release

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local